# Generated by Django 5.0.7 on 2024-08-04 18:17

import brand.models
import ckeditor.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4)),
                ('fa_name', models.CharField(max_length=100, verbose_name='Persian Name')),
                ('en_name', models.CharField(max_length=100, verbose_name='English Name')),
                ('big_logo', models.ImageField(upload_to=brand.models.big_logo_image_path)),
                ('sm_logo', models.ImageField(upload_to=brand.models.sm_logo_image_path)),
                ('descriptions', ckeditor.fields.RichTextField(verbose_name='Description About Brand')),
                ('url', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='brand_slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4)),
                ('slide', models.ImageField(upload_to=brand.models.brand_slide_image_path)),
                ('active', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.brand')),
            ],
        ),
    ]
