# Generated by Django 5.0.7 on 2024-08-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0004_alter_admin_login_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_info',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Null'), (1, 'Male'), (2, 'Female')], default=0),
        ),
        migrations.AlterField(
            model_name='admin_login',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='admin_login',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
