# Generated by Django 5.0.7 on 2024-08-05 13:25

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0005_alter_admin_info_gender_alter_admin_login_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_info',
            name='age',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='admin_info',
            name='birthday_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
