# Generated by Django 5.0.7 on 2024-08-05 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0007_alter_admin_login_brand'),
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_login',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brand.brand'),
        ),
    ]
