# Generated by Django 5.0.7 on 2024-08-11 16:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0008_alter_admin_login_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_codes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4)),
                ('phonenumber', models.CharField(max_length=12, unique=True)),
            ],
        ),
    ]
