# Generated by Django 5.0.7 on 2024-08-23 18:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='player_codes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4)),
                ('phonenumber', models.CharField(max_length=12, unique=True)),
                ('code', models.CharField(max_length=5)),
            ],
        ),
    ]
