# Generated by Django 5.0.7 on 2024-08-24 11:29

import django_jalali.db.models
import jdatetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_player_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_info',
            name='age',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='player_info',
            name='birthday_date',
            field=django_jalali.db.models.jDateField(blank=True, default=jdatetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='player_info',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'Null'), (1, 'Male'), (2, 'Female'), (3, 'Whatyouneed')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player_login',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
