# Generated by Django 5.0.7 on 2024-08-25 00:40

import player.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_alter_player_info_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_info',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=player.models.player_avatar_path),
        ),
    ]
