# Generated by Django 5.0.7 on 2024-08-11 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escaperoom', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='advertising_banner',
        ),
    ]
