# Generated by Django 5.0.7 on 2024-08-19 17:57

import django.db.models.deletion
import escaperoom.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0011_alter_admin_codes_code'),
        ('escaperoom', '0003_advertising_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner_header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=100, verbose_name='eng slide name')),
                ('url', models.CharField(max_length=100, verbose_name='url slide')),
                ('slide', models.ImageField(upload_to=escaperoom.models.home_slide_image_path)),
                ('active', models.BooleanField(default=False)),
                ('admin_login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminstrator.admin_login')),
            ],
        ),
    ]
