# Generated by Django 5.0.7 on 2024-08-15 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_rename_game_closed_session_sold_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sold_time',
            name='admin',
        ),
    ]
