# Generated by Django 5.0.7 on 2024-08-15 23:18

import django.db.models.deletion
import django_jalali.db.models
import jdatetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_remove_sold_time_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='closed_day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4)),
                ('day', django_jalali.db.models.jDateField(default=jdatetime.date.today)),
                ('active', models.BooleanField(default=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
        ),
    ]
