# Generated by Django 5.0.7 on 2024-08-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_game_close_game_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='time',
            new_name='today_time',
        ),
        migrations.RemoveField(
            model_name='game',
            name='close',
        ),
        migrations.AddField(
            model_name='game',
            name='today_close',
            field=models.BooleanField(default=False, verbose_name='today close ?'),
        ),
    ]
