# Generated by Django 5.0.7 on 2024-08-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_rename_today_time_game_all_game_times_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='all_game_times',
        ),
        migrations.AddField(
            model_name='game_time',
            name='number',
            field=models.IntegerField(default=4),
        ),
    ]
