# Generated by Django 5.0.7 on 2024-08-29 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_remove_game_all_game_times_game_time_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game_time',
            name='number',
        ),
        migrations.AddField(
            model_name='game',
            name='game_time_number',
            field=models.IntegerField(default=4),
        ),
    ]
