# Generated by Django 5.0.7 on 2024-08-29 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_remove_game_time_number_game_game_time_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_time_number',
        ),
        migrations.AddField(
            model_name='game_details',
            name='game_time_number',
            field=models.IntegerField(default=4),
        ),
    ]
